<?php

/* 
 * @file
 * Contains \Drupal\space_craft\space_craft.module.
 * 
 * Implements a hook for the Space Craft plugin.
 */

/**
 * Implements hook_probe_info_alter().
 * @param type $probe_plugin_info
 */
function space_craft_probe_info_alter(&$probe_plugin_info) {
  // change the 'description' property for all probes.
   foreach($probe_plugin_info as $plugin_id => $plugin_definition) {
     // Always uppercase the word nasa in probe descriptions
     $probe_plugin_info[$plugin_id]['description'] = str_replace(t('nasa'), t('NASA'), $probe_plugin_info[$plugin_id]['description']);
   }
}