<?php

/**
 * @file
 * A module demonstrating the Block API and by extension the Plugin API
 *  as well as, Drupal coding standards 
 *
 * This module provides a block that lists all of the installed modules in our Drupal system. 
 * It illustrates implementing the Block API and by extension the Plugin API, 
 * as well as, Drupal coding standard.
*/

/**
 * Implements hook_help().
*/
function probe_block_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.probe_block') {
    return t('A probe block demo module.');
  }
}

