# Block schema
# Must be included before first enabling this custom module.
block.settings.probe_block:
  type: block_settings
  mapping:
    number_of_items:
      type: integer
      label: 'Number of items'
    